# Site settings
title: in case you need me
email: lmasamubel1988@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  IM NOT SURE THIS WORKS but if it does im gonna write some stuff there about what this site gonna do or not
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://artstepanyuk.github.io/" # the base hostname & protocol for your site
twitter_username: No Twitter yet
github_username:  ArtStepanyuk

# Build settings
markdown: kramdown
